[project]
name = "mecanica-estadistica"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "nbconvert>=7.16.6",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "numba>=0.62.1",
    "ipywidgets>=8.1.8",
]
