[project]
name = "dinamica-molecular"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10, <3.14"
dependencies = [
    "numba>=0.62.1",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
]
